spring:
  application:
    name: springcloud-portal
---
server:
  port: 8764
spring:
  profiles: portal1
eureka:
  client:
    healthcheck:
      enabled: true
    serviceUrl:
      defaultZone: http://user:password123@localhost:8761/eureka
---
server:
  port: 8765
spring:
  profiles: portal2
eureka:
  client:
    healthcheck:
      enabled: true
    serviceUrl:
      defaultZone: http://user:password123@localhost:8762/eureka
---
server:
  port: 8766
spring:
  profiles: portal3
eureka:
  client:
    healthcheck:
      enabled: true
    serviceUrl:
      defaultZone: http://user:password123@localhost:8763/eureka