spring:
  application:
    name: springcloud-personnel
---
server:
  port: 8767
spring:
  profiles: personnel1
eureka:
  client:
    healthcheck:
      enabled: true
    serviceUrl:
      defaultZone: http://user:password123@localhost:8761/eureka
---
server:
  port: 8768
spring:
  profiles: personnel2
eureka:
  client:
    healthcheck:
      enabled: true
    serviceUrl:
      defaultZone: http://user:password123@localhost:8762/eureka
---
server:
  port: 8769
spring:
  profiles: personnel3
eureka:
  client:
    healthcheck:
      enabled: true
    serviceUrl:
      defaultZone: http://user:password123@localhost:8763/eureka
















